CREATE DATABASE IF NOT EXISTS chicken_run;
USE chicken_run;

CREATE TABLE IF NOT EXISTS farmyard(
    ID int(11) NOT NULL,
    NAME text NOT NULL
);

ALTER TABLE farmyard ADD PRIMARY KEY (ID);
ALTER TABLE farmyard MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

INSERT INTO farmyard(NAME) VALUES("A");
INSERT INTO farmyard(NAME) VALUES("B");
INSERT INTO farmyard(NAME) VALUES("C");

CREATE TABLE IF NOT EXISTS chickens(
    ID int(11) NOT NULL,
    NAME text NOT NULL,
    BIRTHDAY DATE, 
    WEIGHT int(11) NOT NULL,
    STEPS int(11) NOT NULL DEFAULT 0,
    IS_RUNNING boolean NOT NULL DEFAULT FALSE,
    FARM_ID int(11) NULL
);

ALTER TABLE chickens ADD PRIMARY KEY (ID);
ALTER TABLE chickens MODIFY ID int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE chickens ADD FOREIGN KEY (FARM_ID) REFERENCES farmyard(ID); 


INSERT INTO chickens(NAME, BIRTHDAY, WEIGHT, FARM_ID) VALUES ("Gupta", "2005-11-11", 6, 1);
INSERT INTO chickens(NAME, BIRTHDAY, WEIGHT, FARM_ID) VALUES ("Henry", "2002-11-11", 7, 2);





